// <auto-generated />
namespace Library_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ver61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver61));
        
        string IMigrationMetadata.Id
        {
            get { return "201904121909018_ver61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
